baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Web hodierna'
theme = 'hodierno'

[menu]
[[menu.main]]
    name = 'Principal'
    url = '/'
    weight = -120

[[menu.main]]
    name = 'Propósito'
    url = '/proposito/'
    weight = -110

[[menu.main]]
    name = 'Enlaces'
    url = '/enlaces/'
    weight = -100

[[menu.main]]
    name = 'Libros'
    url = '/libros/'
    weight = -90

[permalinks]
    posts = "posts/:filename"